Repository samliew/se-electionbot, pull requests merged in 2021-09, with the labels that each got.

#85 Enhancement for the isActive method + unit tests
  src/election.js
  test/unit/election.js
Labels: improvement

#90 Integrated ChatExchange 0.4.0
  package-lock.json
  package.json
  patches/chatexchange+0.3.0.patch
  src/index.js
Labels: improvement

#97 fixed ChatEventType import
  src/index.js
Labels: bug

#103 Improvements to message guards & tests
  src/guards.js
  src/index.js
  test/unit/guards.js
Labels: improvement

#104 Minor optimizations
  src/election.js
  src/index.js
  test/mocks/nominee.js
  test/unit/election.js
Labels: improvement

#106 WIP: Various optimizations
  src/election.js
  src/index.js
  test/unit/election.js
Labels: improvement

#107 WIP: various optimizations
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
  src/utils.js
  test/unit/utils.js
Labels: improvement

#108 Finally moving BotConfig to a class; various other optimizations
  package-lock.json
  package.json
  src/api.js
  src/config.js
  src/election.js
  src/index.js
  src/score.js
  src/utils.js
Labels: improvement

#111 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: chores

#113 Rescraper class + ScheduledAnnouncement class rework
  src/ScheduledAnnouncement.js
  src/index.js
  src/queue.js
  src/rescraper.js
Labels: improvement

#115 Investigation and updates re #114
  src/ScheduledAnnouncement.js
  src/api.js
  src/commands/index.js
  src/config.js
  src/election.js
  src/index.js
  src/messages.js
  src/queue.js
  src/rescraper.js
  src/score.js
  src/utils.js
  test/mocks/bot.js
  test/unit/api.js
  test/unit/messages.js
  test/unit/package.js
  tsconfig.json
Labels: bug, improvement

#116 Fix for the _sendMessage function
  src/queue.js
  src/rescraper.js
Labels: bug

#118 Bugfixes
  src/election.js
  src/index.js
  src/rescraper.js
  test/unit/election.js
Labels: bug

#120 Add testing coverage (using C8)
  .c8rc
  coverage/base.css
  coverage/block-navigation.js
  coverage/coverage/block-navigation.js.html
  coverage/coverage/index.html
  coverage/coverage/prettify.js.html
  coverage/coverage/sorter.js.html
  coverage/favicon.png
  coverage/index.html
  coverage/prettify.css
  coverage/prettify.js
  coverage/sort-arrow-sprite.png
  coverage/sorter.js
  coverage/src/ScheduledAnnouncement.js.html
  coverage/src/api.js.html
  coverage/src/commands/commands.js.html
  coverage/src/commands/index.html
  coverage/src/commands/index.js.html
  coverage/src/config.js.html
  coverage/src/election.js.html
  coverage/src/guards.js.html
  coverage/src/index.html
  coverage/src/index.js.html
  coverage/src/messages.js.html
  coverage/src/queue.js.html
  coverage/src/random.js.html
  coverage/src/rescraper.js.html
  coverage/src/score.js.html
  coverage/src/utils.js.html
  coverage/src/utils/index.html
  coverage/src/utils/package.js.html
  coverage/test/integration/api.js.html
  coverage/test/integration/index.html
  coverage/test/mocks/bot.js.html
  coverage/test/mocks/index.html
  coverage/test/mocks/nominee.js.html
  coverage/test/unit/api.js.html
  coverage/test/unit/commands.js.html
  coverage/test/unit/election.js.html
  coverage/test/unit/guards.js.html
  coverage/test/unit/index.html
  coverage/test/unit/messages.js.html
  coverage/test/unit/package.js.html
  coverage/test/unit/utils.js.html
  package-lock.json
  package.json
Labels: improvement

#121 Various message-related updates
  src/config.js
  src/index.js
  src/queue.js
Labels: improvement

#122 Modularized server
  src/index.js
  src/server.js
  src/utils.js
Labels: improvement

#124 Minor bugfixes
  src/config.js
  src/index.js
  src/queue.js
Labels: bug

#126 Heroku API
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
  src/election.js
  src/herokuClient.js
  src/index.js
  src/rescraper.js
  src/server.js
  test/integration/heroku-api.js
Labels: feature

#128 Making RandomArray and responseText strictly typed
  src/index.js
  src/queue.js
  src/random.js
Labels: bug

#129 Dependencies
  package-lock.json
  package.json
  src/herokuClient.js
Labels: dependencies, chores

#130 Templating engine for server
  package-lock.json
  package.json
  src/server.js
  static/css/styles.css
  views/config.handlebars
  views/index.handlebars
  views/layouts/main.handlebars
  views/say.handlebars
Labels: feature, do not merge

#131 Minor updates to the server component
  package-lock.json
  package.json
  src/server.js
Labels: chores, improvement
